#!/bin/bash
for i in lig1 lig2 lig3 lig4
do
cd $i
prepare_ligand4=/home/anwesh/softwares/mgltools_x86_64Linux2_1.5.6/bin/pythonsh prepare_ligand4.py -l $i.pdb
prepare_receptor4=/home/anwesh/softwares/mgltools_x86_64Linux2_1.5.6/bin/pythonsh prepare_receptor4.py -r rec.pdb
prepare_gpf4=/home/anwesh/softwares/mgltools_x86_64Linux2_1.5.6/bin/pythonsh prepare_gpf4.py -l $i.pdbqt -r rec.pdbqt -o grid.gpf
autogrid4 -p grid.gpf -l grid.glg
prepare_dpf42=/home/anwesh/softwares/mgltools_x86_64Linux2_1.5.6/bin/pythonsh prepare_dpf42.py -l $i.pdbqt-r rec.pdbqt -o dock.dpf
autodock4 -p dock.dpf -l dock.dlg
cd ..
done
echo SECONDS